// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzzImSJdui8ErLl9P-E-1Uh3FKulXmslY',
    appId: '1:764785964907:web:a4019366ce328cc7ba7e2e',
    messagingSenderId: '764785964907',
    projectId: 'wegotogether-test',
    authDomain: 'wegotogether-test.firebaseapp.com',
    databaseURL: 'https://wegotogether-test-default-rtdb.firebaseio.com',
    storageBucket: 'wegotogether-test.appspot.com',
    measurementId: 'G-YRW1SHBS7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7EE9BLWt0nxm-Jt0o98I4hnRWyjVtXkw',
    appId: '1:764785964907:android:2a1123878d55011eba7e2e',
    messagingSenderId: '764785964907',
    projectId: 'wegotogether-test',
    databaseURL: 'https://wegotogether-test-default-rtdb.firebaseio.com',
    storageBucket: 'wegotogether-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfYtjScoCFe0CZ9f1gzyW2rnxSWlh-oQg',
    appId: '1:764785964907:ios:75ad74a120e73875ba7e2e',
    messagingSenderId: '764785964907',
    projectId: 'wegotogether-test',
    databaseURL: 'https://wegotogether-test-default-rtdb.firebaseio.com',
    storageBucket: 'wegotogether-test.appspot.com',
    iosBundleId: 'com.example.herewego',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfYtjScoCFe0CZ9f1gzyW2rnxSWlh-oQg',
    appId: '1:764785964907:ios:1f06aa2ca7772764ba7e2e',
    messagingSenderId: '764785964907',
    projectId: 'wegotogether-test',
    databaseURL: 'https://wegotogether-test-default-rtdb.firebaseio.com',
    storageBucket: 'wegotogether-test.appspot.com',
    iosBundleId: 'com.example.herewego.RunnerTests',
  );
}
